//
//  VocabData.swift
//  Words
//
//  Created by Julia Teleki on 3/31/26.
//

import Foundation

struct VocabWord: Identifiable, Hashable {
    let id = UUID()
    let word: String
    let definition: String?
    let synonyms: [String]

    init(word: String, definition: String?, synonyms: [String] = []) {
        self.word = word
        self.definition = definition
        self.synonyms = synonyms
    }
}

enum VocabData {
    static let vocab: [VocabWord] = [
        VocabWord(word: "abhor", definition: "To regard as horrifying or detestable; to feel great repugnance toward.", synonyms: ["hate", "dislike"]),
        VocabWord(word: "absolve", definition: "To pronounce free from or give absolution for a penalty, blame, or guilt.", synonyms: ["forgive", "clear", "free"]),
        VocabWord(word: "accompanied", definition: "Having accompaniment; being part of a group of at least two.", synonyms: ["associated", "connected", "attended"]),
        VocabWord(word: "accosted", definition: "Supported on both sides by other charges.", synonyms: ["address", "spoke"]),
        VocabWord(word: "acolyte", definition: "An attendant, assistant, or follower.", synonyms: ["helper", "assistant", "follower"]),
        VocabWord(word: "acrimonious", definition: "Angry, acid, and sharp in delivering argumentative replies: bitter, mean-spirited, sharp in language or tone.", synonyms: ["bitter", "harsh", "angry acid"]),
        VocabWord(word: "acuity", definition: "The ability to think, see, or hear clearly.", synonyms: ["sharpness", "clarity"]),
        VocabWord(word: "ad nauseam", definition: "Having been done or repeated so often that it has become annoying or tiresome.", synonyms: ["too much", "repeatedly", "endlessly"]),
        VocabWord(word: "adjacent", definition: "Lying next to, close, or contiguous; neighboring; bordering on.", synonyms: ["close", "near", "connected"]),
        VocabWord(word: "admonish", definition: "To advise against wrongdoing; to caution; to warn against danger or an offense.", synonyms: ["caution", "warn"]),
        VocabWord(word: "adulation", definition: "Flattery; fulsome praise.", synonyms: ["praise", "flattery"]),
        VocabWord(word: "affliction", definition: "A state of pain, suffering, distress or agony.", synonyms: ["pain", "suffering", "trouble"]),
        VocabWord(word: "agile", definition: "Of or relating to agile software development, a technique for iterative and incremental development of software involving collaboration between teams.", synonyms: ["quick", "fast", "nimble"]),
        VocabWord(word: "akin", definition: "Allied by nature; similar; partaking of the same properties; of the same kind.", synonyms: ["like", "similar", "related"]),
        VocabWord(word: "albeit", definition: "Although; even though.", synonyms: ["though", "although", "even though"]),
        VocabWord(word: "altercation", definition: "An angry or heated dispute.", synonyms: ["dispute", "angry", "heated dispute"]),
        VocabWord(word: "amenable", definition: "Willing to respond to persuasion or suggestions.", synonyms: ["willing", "open"]),
        VocabWord(word: "amiable", definition: "Friendly; kind; sweet; gracious.", synonyms: ["friendly"]),
        VocabWord(word: "amoral", definition: "Not believing in or caring for morality and immorality.", synonyms: ["wrong", "uncaring"]),
        VocabWord(word: "anachronism", definition: "A person or thing which seems to belong to a different time or period of time.", synonyms: ["outdated", "old fashioned"]),
        VocabWord(word: "ancillary", definition: "Subordinate; secondary; auxiliary.", synonyms: ["extra", "helper"]),
        VocabWord(word: "anemic", definition: "Of, pertaining to, or suffering from anemia.", synonyms: ["weak"]),
        VocabWord(word: "animosity", definition: "Violent hatred leading to active opposition; active enmity; energetic dislike.", synonyms: ["hatred", "anger"]),
        VocabWord(word: "antagonizing", definition: "Tending to antagonize.", synonyms: ["annoying", "provoking", "irritating"]),
        VocabWord(word: "antecedent", definition: "a word, phrase, or clause referred to by a pronoun", synonyms: ["previous", "prior", "precursor"]),
        VocabWord(word: "apathy", definition: "Lack of emotion or motivation; lack of interest or enthusiasm towards something; disinterest.", synonyms: ["indifference", "disinterest"]),
        VocabWord(word: "apocalypse", definition: "A huge disaster; a cataclysmic event; destruction or ruin of large scope and scale.", synonyms: ["grip", "doom", "revelation"]),
        VocabWord(word: "approximately", definition: "Imprecise but close to in quantity or amount.", synonyms: ["roughly", "amount"]),
        VocabWord(word: "aptly", definition: "In an apt or suitable manner; fittingly; appropriately; suitably.", synonyms: ["well", "appropriately"]),
        VocabWord(word: "ardent", definition: "Full of ardor; expressing passion, spirit, or enthusiasm.", synonyms: ["passionate", "eager"]),
        VocabWord(word: "asinine", definition: "Very foolish; failing to exercise intelligence or judgement or rationality.", synonyms: ["foolish", "stupid"]),
        VocabWord(word: "aspirational", definition: "Being ambitious.", synonyms: ["ideal", "challenging", "far reaching"]),
        VocabWord(word: "assent", definition: "To agree to a proposal.", synonyms: ["agree", "approval"]),
        VocabWord(word: "astonishing", definition: "Causing astonishment.", synonyms: ["impressive"]),
        VocabWord(word: "astounding", definition: "That astounds or astound.", synonyms: ["incredible", "impressive"]),
        VocabWord(word: "atrocious", definition: "Very bad; abominable, disgusting.", synonyms: ["awful", "terrible"]),
        VocabWord(word: "audacious", definition: "Showing willingness to take bold risks; recklessly daring.", synonyms: ["bold", "brave"]),
        VocabWord(word: "audacity", definition: "Insolent boldness, especially when imprudent or unconventional.", synonyms: ["boldness", "nerve"]),
        VocabWord(word: "baffling", definition: "Puzzling, perplexing, bewildering.", synonyms: ["hard", "difficult", "problematic"]),
        VocabWord(word: "beatific", definition: "Blessed, blissful, heavenly.", synonyms: ["good"]),
        VocabWord(word: "bellend", definition: "A foolish or contemptible person.", synonyms: ["fool", "idiot", "jerk"]),
        VocabWord(word: "benevolent", definition: "Having a disposition to do good.", synonyms: ["good"]),
        VocabWord(word: "bile", definition: "A bitter brownish-yellow or greenish-yellow secretion produced by the liver, stored in the gall bladder, and discharged into the duodenum where it aids the process of digestion.", synonyms: ["anger", "bitterness"]),
        VocabWord(word: "bitter", definition: "Having an acrid taste.", synonyms: ["angry", "sour"]),
        VocabWord(word: "bizarre", definition: "Strangely unconventional; highly unusual and different from common experience, often in an extravagant, fantastic, and/or conspicuous way.", synonyms: ["weird", "strange", "odd"]),
        VocabWord(word: "boorish", definition: "Behaving as a boor; rough in manners.", synonyms: ["rude", "crude"]),
        VocabWord(word: "brazen", definition: "Shameless or impudent; shocking or audacious; brash.", synonyms: ["bold", "shameless"]),
        VocabWord(word: "brigade", definition: "A group of people organized for a common purpose.", synonyms: ["group", "team"]),
        VocabWord(word: "bright", definition: "Emitting much light; visually dazzling; luminous, lucent, radiant.", synonyms: ["light", "lucent"]),
        VocabWord(word: "brocade", definition: "rich fabric with raised pattern", synonyms: ["fabric", "textile"]),
        VocabWord(word: "brutes", definition: "Brutal; cruel; fierce; ferocious; savage; pitiless, without intelligence or reason.", synonyms: ["savage", "brutal"]),
        VocabWord(word: "bugger", definition: "To have anal sex with, sodomize.", synonyms: ["jerk", "fool"]),
        VocabWord(word: "callous", definition: "Emotionally hardened; unfeeling and indifferent to the suffering/feelings of others.", synonyms: ["cold", "cruel", "uncaring"]),
        VocabWord(word: "capacity", definition: "The ability to hold, receive, or absorb.", synonyms: ["content", "mental ability", "capability"]),
        VocabWord(word: "capitulate", definition: "To surrender on stipulated terms, end all resistance, give up, go along with or comply.", synonyms: ["give up", "surrender"]),
        VocabWord(word: "cautious", definition: "Using or exercising caution; careful; tentative.", synonyms: ["moderate", "using", "exercising caution"]),
        VocabWord(word: "cavalierly", definition: "In a cavalier manner.", synonyms: ["lightly"]),
        VocabWord(word: "ceding", definition: "The act of ceding.", synonyms: ["giving up", "handing over"]),
        VocabWord(word: "chagrin", definition: "Distress of mind caused by a failure of aims or plans, want of appreciation, mistakes etc; vexation or mortification.", synonyms: ["humble"]),
        VocabWord(word: "chaise", definition: "A chaise longue.", synonyms: ["chair", "lounge", "sofa"]),
        VocabWord(word: "charismatic", definition: "Of, related to, or having charisma: having a form of compelling charm which inspires devotion in others due to their strength of character and being full of personality; charming, fascinating, magnetic.", synonyms: ["leader", "magnetic", "attractive"]),
        VocabWord(word: "charitability", definition: "Charitableness.", synonyms: ["charity", "philanthropy"]),
        VocabWord(word: "charlatan", definition: "A malicious trickster; a fake person, especially one who deceives for personal profit.", synonyms: ["fake", "fraud"]),
        VocabWord(word: "chaste", definition: "Sexually pure, abstaining from immoral or unlawful sexual intercourse.", synonyms: ["plain", "pure", "moral"]),
        VocabWord(word: "chattel", definition: "Tangible, movable property.", synonyms: ["property", "goods"]),
        VocabWord(word: "chic", definition: "Elegant, stylish.", synonyms: ["smart", "stylish", "elegant stylish"]),
        VocabWord(word: "chicanery", definition: "trickery", synonyms: ["trickery", "deceit"]),
        VocabWord(word: "churned", definition: "To stop using a company's product or service.", synonyms: ["boil", "service"]),
        VocabWord(word: "circumnavigate", definition: "To travel completely around somewhere or something, especially by sail.", synonyms: ["go around", "circle"]),
        VocabWord(word: "classy", definition: "Elegant, highly stylish or fashionable.", synonyms: ["stylish", "fashionable"]),
        VocabWord(word: "clause", definition: "a grammatical unit that contains both a subject and a verb", synonyms: ["proposition", "verb"]),
        VocabWord(word: "clever", definition: "Quick to understand, learn, and devise or apply ideas; intelligent.", synonyms: ["intelligent", "apply ideas"]),
        VocabWord(word: "clusterfuck", definition: "A badly mismanaged or chaotic situation.", synonyms: ["disaster", "mess", "chaotic situation"]),
        VocabWord(word: "coalesced", definition: "Joined together into a whole.", synonyms: ["consolidated"]),
        VocabWord(word: "coherence", definition: "the quality of being logical and consistent", synonyms: ["logic", "clarity", "consistency"]),
        VocabWord(word: "cohorts", definition: "A group of people supporting the same thing or person.", synonyms: ["group", "allies"]),
        VocabWord(word: "comical", definition: "Funny, whimsically amusing.", synonyms: ["humorous", "amusing"]),
        VocabWord(word: "compelling", definition: "Very interesting; able to capture and hold one's attention.", synonyms: ["powerful", "engaging"]),
        VocabWord(word: "compounded", definition: "Compound; composite; resulting from the interaction and combination of multiple parts.", synonyms: ["add", "combined", "accumulated"]),
        VocabWord(word: "comprehend", definition: "To understand or grasp fully and thoroughly; to plumb.", synonyms: ["cover", "embrace", "understand"]),
        VocabWord(word: "compunction", definition: "A pricking of conscience or a feeling of regret, especially one which is slight or fleeting.", synonyms: ["guilt", "regret"]),
        VocabWord(word: "concomitantly", definition: "At the same time as something else.", synonyms: ["together", "simultaneously"]),
        VocabWord(word: "condemnation", definition: "The act of condemning or pronouncing to be wrong.", synonyms: ["curse"]),
        VocabWord(word: "confection", definition: "A food item prepared very sweet, frequently decorated in fine detail, and often preserved with sugar, such as a candy, sweetmeat, fruit preserve, pastry, or cake.", synonyms: ["sweet", "cake"]),
        VocabWord(word: "confessional", definition: "A small room where confession—the Sacrament of Penance—is performed in private with a priest.", synonyms: ["confession", "private booth"]),
        VocabWord(word: "congeal", definition: "To change from a liquid to solid state, perhaps due to cold; called to freeze in nontechnical usage.", synonyms: ["set", "gel"]),
        VocabWord(word: "conjunction", definition: "a word that joins words, phrases, or clauses", synonyms: ["connector", "linker", "clauses"]),
        VocabWord(word: "consequences", definition: "An old-fashioned parlour game describing the meeting of a lady and gentleman and the ensuing events, each player in turn writing a part of the story, not knowing what the others have written.", synonyms: ["result", "effect", "outcome"]),
        VocabWord(word: "constituency", definition: "A district represented by one or more elected officials.", synonyms: ["voters", "district"]),
        VocabWord(word: "constituents", definition: "A resident of an area represented by an elected official, particularly in relation to that official.", synonyms: ["parts", "members"]),
        VocabWord(word: "contempt", definition: "The state or act of contemning; the feeling or attitude of regarding someone or something as inferior, base, or worthless; scorn, disdain.", synonyms: ["spite"]),
        VocabWord(word: "contrition", definition: "remorse", synonyms: ["regret", "guilt"]),
        VocabWord(word: "cooing", definition: "A stage in the development of child language after crying and before babbling; the baby is able to control their sounds but tongue muscles are not well developed.", synonyms: ["soft sounds", "gentle sounds"]),
        VocabWord(word: "coursing", definition: "The sport of chasing wild animals, especially hares, with dogs by sight rather than by scent.", synonyms: ["class", "trend", "naturally"]),
        VocabWord(word: "covert", definition: "Secret, surreptitious, concealed.", synonyms: ["secret", "hidden"]),
        VocabWord(word: "crisis", definition: "An unstable situation, in political, social, economic or military affairs, especially one involving an impending abrupt change.", synonyms: ["situation", "emergency", "dilemma"]),
        VocabWord(word: "cross", definition: "A geometrical figure consisting of two straight lines or bars intersecting each other such that at least one of them is bisected by the other.", synonyms: ["mark", "sweep", "queer"]),
        VocabWord(word: "crusade", definition: "A grand, concerted effort towards some purportedly worthy cause.", synonyms: ["drive", "cause", "effort"]),
        VocabWord(word: "cunning", definition: "Sly; crafty; clever in surreptitious behaviour.", synonyms: ["craft", "clever"]),
        VocabWord(word: "cursory", definition: "Hasty or superficial.", synonyms: ["quick", "brief"]),
        VocabWord(word: "cynical", definition: "Skeptical of the integrity, sincerity, or motives of others.", synonyms: ["doubtful", "skeptical"]),
        VocabWord(word: "dainty", definition: "Elegant; delicately small and pretty.", synonyms: ["refined", "delicate", "exquisite"]),
        VocabWord(word: "dapper", definition: "Stylishly dressed, neatly dressed, spiffy.", synonyms: ["smart", "stylish"]),
        VocabWord(word: "dastardly", definition: "In the manner of a dastard; marked by cowardice; pusillanimous.", synonyms: ["coward"]),
        VocabWord(word: "dauntless", definition: "Invulnerable to fear or intimidation.", synonyms: ["brave", "fearless"]),
        VocabWord(word: "debauchery", definition: "An excessive indulgence in sensual pleasures; scandalous and immoral activities; involving sex, alcohol, or drugs without inhibition.", synonyms: ["orgy", "riot"]),
        VocabWord(word: "declarative", definition: "a sentence that makes a statement", synonyms: ["statement", "stating"]),
        VocabWord(word: "decorum", definition: "Appropriate social behavior.", synonyms: ["manners", "politeness"]),
        VocabWord(word: "defiant", definition: "Boldly resisting opposition.", synonyms: ["rebellious", "resistant"]),
        VocabWord(word: "demarcated", definition: "To mark the limits or boundaries of something; to delimit.", synonyms: ["bound", "bounded"]),
        VocabWord(word: "demeaning", definition: "Degrading; that degrades.", synonyms: ["insulting", "belittling", "humiliating"]),
        VocabWord(word: "demerit", definition: "A quality of being inadequate; a disadvantage, a fault.", synonyms: ["sub", "fault", "weakness"]),
        VocabWord(word: "demure", definition: "Modest, quiet, reserved, or serious.", synonyms: ["modest", "shy"]),
        VocabWord(word: "deplorable", definition: "Deserving strong condemnation; shockingly bad, wretched.", synonyms: ["sad"]),
        VocabWord(word: "depreciating", definition: "That is declining in value.", synonyms: ["decreasing"]),
        VocabWord(word: "derision", definition: "mockery", synonyms: ["contempt"]),
        VocabWord(word: "desolate", definition: "Deserted and devoid of inhabitants.", synonyms: ["stark"]),
        VocabWord(word: "detractor", definition: "A person who belittles the worth of another person or cause.", synonyms: ["critic", "opponent"]),
        VocabWord(word: "detritus", definition: "waste", synonyms: ["dust", "junk", "debris"]),
        VocabWord(word: "devious", definition: "Cunning or deceiving, not straightforward or honest, not frank.", synonyms: ["sneaky", "dishonest"]),
        VocabWord(word: "diffuse", definition: "To spread over or through as in air, water, or other matter, especially by fluid motion or passive means.", synonyms: ["passive means"]),
        VocabWord(word: "dilapidated", definition: "Having fallen into a state of disrepair or deterioration, especially through neglect.", synonyms: ["damaged"]),
        VocabWord(word: "discarded", definition: "Disposed of as useless.", synonyms: ["waste", "cast off", "useless"]),
        VocabWord(word: "disconcerting", definition: "Tending to cause discomfort, uneasiness or alarm.", synonyms: ["upsetting", "unsettling"]),
        VocabWord(word: "discretion", definition: "The ability to make wise choices or decisions.", synonyms: ["decisions"]),
        VocabWord(word: "disembodied", definition: "Having no material body, immaterial; incorporeal or insubstantial.", synonyms: ["ghostly", "without body"]),
        VocabWord(word: "disemboweled", definition: "To take or let out the bowels or interior parts of; to eviscerate.", synonyms: ["draw", "destroyed", "take"]),
        VocabWord(word: "disingenuous", definition: "Not ingenuous; not frank or open.", synonyms: ["dishonest", "insincere"]),
        VocabWord(word: "dismal", definition: "Causing despair; gloomy and bleak.", synonyms: ["blue", "grim", "causing despair"]),
        VocabWord(word: "disordered", definition: "Chaotic; without clear order; in a state of disorder.", synonyms: ["confused", "upset", "chaotic"]),
        VocabWord(word: "disquieting", definition: "Causing mental trouble or anguish; upsetting; making uneasy.", synonyms: ["disturbing", "uncomfortable"]),
        VocabWord(word: "distasteful", definition: "Unpleasant.", synonyms: ["wicked", "foul", "unpleasant"]),
        VocabWord(word: "disturbed", definition: "Having been altered or changed.", synonyms: ["unstable", "troubled", "distressed"]),
        VocabWord(word: "dreadful", definition: "Genuinely horrific, awful, or alarming; dangerous, risky.", synonyms: ["bad", "dread"]),
        VocabWord(word: "dreary", definition: "Drab; dark, colorless, or cheerless.", synonyms: ["dull"]),
        VocabWord(word: "drily", definition: "Alternative spelling of dryly.", synonyms: ["dryly", "plainly"]),
        VocabWord(word: "dubious", definition: "Arousing doubt; questionable; open to suspicion.", synonyms: ["doubtful", "questionable"]),
        VocabWord(word: "dull", definition: "Boring; not exciting or interesting.", synonyms: ["soft", "heavy", "boring"]),
        VocabWord(word: "duplicitous", definition: "Given to or marked by deliberate deceptiveness in behavior or speech.", synonyms: ["deceitful", "dishonest"]),
        VocabWord(word: "dwell", definition: "To live; to reside.", synonyms: ["live", "lie", "worry"]),
        VocabWord(word: "dynamic", definition: "Changing; active; in motion.", synonyms: ["active", "kinetic", "changing"]),
        VocabWord(word: "dystopian", definition: "Dire; characterized by human suffering or misery.", synonyms: ["bleak", "dark"]),
        VocabWord(word: "earnest", definition: "Gravity; serious purpose; earnestness.", synonyms: ["serious", "gravity"]),
        VocabWord(word: "ebullient", definition: "enthusiastic, or a bubbling liquid", synonyms: ["enthusiastic", "excited"]),
        VocabWord(word: "ecstatic", definition: "Extremely happy.", synonyms: ["extremely happy"]),
        VocabWord(word: "effeminate", definition: "Of a boy or man, exhibiting behavior or mannerisms considered typical of a woman or unmasculine.", synonyms: ["soft", "weak"]),
        VocabWord(word: "effervescent", definition: "Giving off bubbles; fizzy.", synonyms: ["bubbly", "sparkling"]),
        VocabWord(word: "egregious", definition: "Outrageously bad; shocking.", synonyms: ["awful", "shocking"]),
        VocabWord(word: "elated", definition: "Extremely happy and excited; delighted; pleased, euphoric.", synonyms: ["high", "sublime", "extremely happy"]),
        VocabWord(word: "elevated", definition: "Raised, usually above ground level.", synonyms: ["high", "raised", "overhead"]),
        VocabWord(word: "eloquent", definition: "Fluently persuasive and articulate.", synonyms: ["clear", "articulate"]),
        VocabWord(word: "eluded", definition: "To evade or escape from , especially by using cunning or skill.", synonyms: ["slip", "avoided", "skill"]),
        VocabWord(word: "elusive", definition: "Evading capture, comprehension or remembrance.", synonyms: ["hard to find", "slippery"]),
        VocabWord(word: "emaciated", definition: "Thin or haggard, especially from hunger or disease.", synonyms: ["thin", "skinny"]),
        VocabWord(word: "emanating", definition: "To come from a source; issue from.", synonyms: ["give forth", "arising", "arriving"]),
        VocabWord(word: "emboldened", definition: "Having been made bold.", synonyms: ["bold", "encouraged", "animated"]),
        VocabWord(word: "emphysema", definition: "enlarged damaged lungs", synonyms: ["lung disease", "breathing illness"]),
        VocabWord(word: "emulator", definition: "A piece of software or hardware that simulates another system.", synonyms: ["rival", "emulation"]),
        VocabWord(word: "enable", definition: "To make somebody able ; to give sufficient ability or power to do or to be; to give strength or ability to.", synonyms: ["afford", "empower"]),
        VocabWord(word: "enchanting", definition: "Having the ability to enchant; charming, delightful.", synonyms: ["attractive"]),
        VocabWord(word: "endearing", definition: "Inspiring affection or love, often in a childlike way.", synonyms: ["lovely", "pleasant", "adorable"]),
        VocabWord(word: "endurance", definition: "The measure of a person's stamina or persistence.", synonyms: ["survival", "persistence"]),
        VocabWord(word: "enormous", definition: "very large in size", synonyms: ["big", "huge", "massive"]),
        VocabWord(word: "entitlement", definition: "The right to have something, whether actual or perceived.", synonyms: ["right", "privilege"]),
        VocabWord(word: "entreatingly", definition: "In an entreating manner.", synonyms: ["pleadingly", "begging"]),
        VocabWord(word: "entropy", definition: "A measure of the disorder present in a system.", synonyms: ["information"]),
        VocabWord(word: "envious", definition: "Feeling or exhibiting envy; jealously desiring the excellence or good fortune of another; maliciously grudging.", synonyms: ["jealous", "feeling"]),
        VocabWord(word: "ephemeral", definition: "Lasting for a short period of time.", synonyms: ["brief", "temporary"]),
        VocabWord(word: "erratic", definition: "Unsteady, random; prone to unexpected changes; not consistent.", synonyms: ["wandering"]),
        VocabWord(word: "eschews", definition: "To avoid; to shun, to shy away from.", synonyms: ["avoids", "avoid"]),
        VocabWord(word: "esoteric", definition: "obscure", synonyms: ["obscure", "specialized"]),
        VocabWord(word: "eviscerated", definition: "To disembowel; to remove the viscera.", synonyms: ["gutted", "emptied", "destroyed"]),
        VocabWord(word: "exclamatory", definition: "a sentence that expresses strong feeling", synonyms: ["emphatic", "excited"]),
        VocabWord(word: "exorbitant", definition: "Exceeding proper limits; excessive or unduly high; extravagant.", synonyms: ["expensive", "overpriced"]),
        VocabWord(word: "extrapolate", definition: "To infer by extending known information.", synonyms: ["infer", "project"]),
        VocabWord(word: "facade", definition: "The face of a building, especially the front view or elevation.", synonyms: ["wall", "window dressing", "elevation"]),
        VocabWord(word: "facet", definition: "Any one of the flat surfaces cut into a gem.", synonyms: ["stream", "aspect", "strand"]),
        VocabWord(word: "facetious", definition: "Treating serious issues with inappropriate humour; flippant.", synonyms: ["joking", "not serious"]),
        VocabWord(word: "fallacies", definition: "An argument, or apparent argument, which professes to be decisive of the matter at issue, while in reality it is not; a specious argument.", synonyms: ["errors", "mistakes", "argument"]),
        VocabWord(word: "famished", definition: "Extremely hungry.", synonyms: ["sharp set", "hungry", "extremely hungry"]),
        VocabWord(word: "fanged", definition: "Equipped with fangs.", synonyms: ["sharp toothed", "toothed"]),
        VocabWord(word: "farce", definition: "A style of humor marked by broad improbabilities with little regard to regularity or method.", synonyms: ["satire", "method"]),
        VocabWord(word: "fasciculation", definition: "brief, spontaneous muscle contraction", synonyms: ["twitch", "muscle twitch"]),
        VocabWord(word: "fascinating", definition: "Having interesting qualities; captivating; attractive.", synonyms: ["interesting", "captivating"]),
        VocabWord(word: "fastidious", definition: "Excessively particular, demanding, or fussy about details, especially about tidiness and cleanliness.", synonyms: ["picky", "fussy"]),
        VocabWord(word: "faux", definition: "Fake or artificial.", synonyms: ["false", "artificial", "fake"]),
        VocabWord(word: "fawn", definition: "A young deer.", synonyms: ["creep", "young deer"]),
        VocabWord(word: "fecund", definition: "fertile", synonyms: ["fertile", "productive"]),
        VocabWord(word: "feign", definition: "To make a false show or pretence of; to counterfeit or simulate.", synonyms: ["affect", "assume", "simulate"]),
        VocabWord(word: "feral", definition: "Wild; untamed.", synonyms: ["wild", "brutal", "savage"]),
        VocabWord(word: "fervor", definition: "An intense, heated emotion; passion, ardor.", synonyms: ["passion", "intensity"]),
        VocabWord(word: "fetid", definition: "Foul-smelling, stinking.", synonyms: ["foul", "smelly"]),
        VocabWord(word: "flabbergasted", definition: "Appalled, annoyed, exhausted or disgusted.", synonyms: ["shocked", "amazed"]),
        VocabWord(word: "folly", definition: "Foolishness that results from a lack of foresight or lack of practicality.", synonyms: ["foolishness", "mistake"]),
        VocabWord(word: "forensic", definition: "Relating to the use of science and technology in the investigation and establishment of facts or evidence in a court of law.", synonyms: ["statutory", "examiner"]),
        VocabWord(word: "forevermore", definition: "At any or all times in the future; forever.", synonyms: ["forth"]),
        VocabWord(word: "forsaken", definition: "Deserted; abandoned.", synonyms: ["abandoned", "deserted"]),
        VocabWord(word: "fossilized", definition: "In a state of fossilization; preserved in rock.", synonyms: ["fossil", "rigid"]),
        VocabWord(word: "fragile", definition: "Easily broken, not sturdy; of delicate material.", synonyms: ["weak", "delicate"]),
        VocabWord(word: "fragment", definition: "an incomplete sentence", synonyms: ["piece", "portion", "incomplete sentence"]),
        VocabWord(word: "fraudulent", definition: "Dishonest; based on fraud or deception.", synonyms: ["fake", "dishonest", "false"]),
        VocabWord(word: "fraught", definition: "Followed by with: carrying, or charged or loaded up with ; accompanied by; entailing.", synonyms: ["tense", "troubled"]),
        VocabWord(word: "froideur", definition: "coolness, reserve between people", synonyms: ["coolness", "distance"]),
        VocabWord(word: "fruition", definition: "The fulfillment of something worked for.", synonyms: ["success", "achievement", "realization"]),
        VocabWord(word: "fruitless", definition: "Unproductive, useless.", synonyms: ["useless", "failed"]),
        VocabWord(word: "gall", definition: "Impudence or brazenness; temerity; chutzpah.", synonyms: ["nerve", "audacity"]),
        VocabWord(word: "gallivanting", definition: "Roaming about for pleasure.", synonyms: ["roaming"]),
        VocabWord(word: "gauche", definition: "Awkward or lacking in social graces; bumbling; apt to make gaffes.", synonyms: ["awkward", "clumsy"]),
        VocabWord(word: "gauge", definition: "A measure; a standard of measure; an instrument to determine dimensions, distance, or capacity; a standard.", synonyms: ["judge", "estimate", "approximate"]),
        VocabWord(word: "gaunt", definition: "Unhealthily thin, as from hunger or illness: drawn, emaciated, haggard.", synonyms: ["thin", "lean"]),
        VocabWord(word: "glamorous", definition: "Having glamour; stylish.", synonyms: ["good looking", "exciting", "handsome"]),
        VocabWord(word: "glowering", definition: "The act of giving a glower.", synonyms: ["dark"]),
        VocabWord(word: "gracious", definition: "Kind and warmly courteous.", synonyms: ["good", "refined"]),
        VocabWord(word: "grandeur", definition: "The state of being grand or splendid; magnificence.", synonyms: ["splendid"]),
        VocabWord(word: "gratuitous", definition: "Unjustified or unnecessary; not called for by the circumstances.", synonyms: ["unnecessary", "extra"]),
        VocabWord(word: "guise", definition: "An external appearance in manner or dress; an appropriate indication or expression; a garb; a shape.", synonyms: ["appearance", "cover"]),
        VocabWord(word: "haggard", definition: "Looking exhausted, worried, or poor in condition.", synonyms: ["thin", "drawn", "lean"]),
        VocabWord(word: "harbinger", definition: "A person or thing that foreshadows or foretells the coming of someone or something.", synonyms: ["sign", "warning"]),
        VocabWord(word: "harrowing", definition: "Causing pain or distress; harrying.", synonyms: ["painful", "disturbing"]),
        VocabWord(word: "hearty", definition: "Warm and cordial towards another person.", synonyms: ["complete", "warm", "substantial"]),
        VocabWord(word: "hedonistic", definition: "Devoted to pleasure.", synonyms: ["pleasure seeking", "self indulgent"]),
        VocabWord(word: "heretic", definition: "Someone whose beliefs are contrary to the fundamental tenets of a religion they claim to belong to.", synonyms: ["rebel", "dissenter"]),
        VocabWord(word: "hermeneutical", definition: "concerning interpretation", synonyms: ["interpretive", "explanatory"]),
        VocabWord(word: "heroic", definition: "Courageous; displaying heroism.", synonyms: ["large", "bold", "desperate"]),
        VocabWord(word: "hierarchy", definition: "A social, religious, economic or political system or organization in which people or groups of people are ranked with some superior to others based on their status, authority or some other trait.", synonyms: ["ranking", "order"]),
        VocabWord(word: "hive-mind", definition: "A shared group consciousness or collective way of thinking.", synonyms: ["groupthink", "shared thinking"]),
        VocabWord(word: "hounding", definition: "Pursuit, especially when persistent or relentless.", synonyms: ["hunt", "heel", "hound dog"]),
        VocabWord(word: "house of cards", definition: "A structure or argument built on a shaky foundation.", synonyms: ["deck", "pyramid", "structure"]),
        VocabWord(word: "humorous", definition: "Full of humor or arousing laughter; funny.", synonyms: ["funny", "comical"]),
        VocabWord(word: "humunculi", definition: "Small artificial humanlike figures; a misspelling or variant of homunculi.", synonyms: ["little figures", "miniatures", "artificial beings"]),
        VocabWord(word: "hybrid", definition: "Something of mixed origin or composition; often, a tool or technology that combines the benefits of formerly separate tools or technologies.", synonyms: ["crossed", "composition"]),
        VocabWord(word: "hyperbole", definition: "an exaggerated statement", synonyms: ["exaggeration", "overstatement"]),
        VocabWord(word: "hypergamy", definition: "marrying up", synonyms: ["marrying up", "social climbing"]),
        VocabWord(word: "idempotent", definition: "Such that, when performed multiple times on the same subject, it has no further effect on its subject after the first time it is performed.", synonyms: ["same result", "repeat safe"]),
        VocabWord(word: "idyllic", definition: "Extremely happy, peaceful, or picturesque.", synonyms: ["perfect", "pleasant", "pastoral"]),
        VocabWord(word: "ignoramous", definition: "Nonstandard form of ignoramus.", synonyms: ["know everything", "non specialist", "na ve"]),
        VocabWord(word: "imbalance", definition: "The property of not being in balance.", synonyms: ["instability"]),
        VocabWord(word: "imbibe", definition: "To drink.", synonyms: ["draw", "suck", "absorb"]),
        VocabWord(word: "immense", definition: "Huge, gigantic, very large.", synonyms: ["big", "large", "huge"]),
        VocabWord(word: "imminent", definition: "About to happen, occur, or take place very soon, especially of something which won't last long.", synonyms: ["near", "coming soon"]),
        VocabWord(word: "impenetrable", definition: "Incomprehensible; fathomless; inscrutable.", synonyms: ["hard to understand", "impossible to enter"]),
        VocabWord(word: "imperative", definition: "a sentence that gives a command", synonyms: ["command", "mandatory", "urgent"]),
        VocabWord(word: "implode", definition: "To collapse or burst inward violently.", synonyms: ["go off", "chinese", "melt"]),
        VocabWord(word: "impropriety", definition: "The condition of being improper.", synonyms: ["liberty", "familiarity"]),
        VocabWord(word: "inadequacies", definition: "A lack of competence or ability.", synonyms: ["defects", "deficiencies", "ability"]),
        VocabWord(word: "inadvertently", definition: "Unintentionally; because of an oversight.", synonyms: ["accidentally", "by mistake"]),
        VocabWord(word: "inane", definition: "Lacking sense or meaning, often to the point of boredom or annoyance.", synonyms: ["silly", "empty"]),
        VocabWord(word: "inanity", definition: "nonsensical remark", synonyms: ["nonsense", "silliness"]),
        VocabWord(word: "incandescent", definition: "Emitting light as a result of being heated.", synonyms: ["hot", "light", "glorious"]),
        VocabWord(word: "incantation", definition: "The act or process of using formulas and/or usually rhyming words, sung or spoken, with occult ceremonies, for the purpose of raising spirits, producing enchantment, or creating other magical results.", synonyms: ["average", "charm", "spell"]),
        VocabWord(word: "incentive", definition: "Something that motivates, rouses, or encourages.", synonyms: ["bonus", "motivational", "encourages"]),
        VocabWord(word: "incoherent", definition: "Not making logical sense; not logically connected or consistent.", synonyms: ["confused"]),
        VocabWord(word: "indignant", definition: "Showing anger or indignation, especially at something unjust or wrong.", synonyms: ["angry", "wrong", "showing anger"]),
        VocabWord(word: "indiscernible", definition: "Not capable of being discerned or perceived.", synonyms: ["perceived"]),
        VocabWord(word: "indiscriminately", definition: "In an indiscriminate manner.", synonyms: ["randomly", "widely"]),
        VocabWord(word: "indulgent", definition: "Disposed or prone to indulge, humor, gratify, or yield to one's own or another's desires, etc., or to be compliant, lenient, or forbearing.", synonyms: ["gay", "soft", "disposed"]),
        VocabWord(word: "inexplicable", definition: "Impossible to explain; not easily accounted for.", synonyms: ["deep"]),
        VocabWord(word: "inextricably", definition: "In an inextricable manner.", synonyms: ["tightly", "inseparably"]),
        VocabWord(word: "infantilization", definition: "The act or process of infantilizing, treating a non-infant as an infant, or more generally treating an adult like a young child.", synonyms: ["treating like a child", "patronizing"]),
        VocabWord(word: "ingenious", definition: "Of a person, displaying genius or brilliance; inventive.", synonyms: ["clever", "inventive"]),
        VocabWord(word: "initial", definition: "The first letter of a word or a name, especially of a person's full name.", synonyms: ["first", "original", "primary"]),
        VocabWord(word: "initiative", definition: "A beginning; a first move.", synonyms: ["first", "opening", "maiden"]),
        VocabWord(word: "innocuous", definition: "Harmless; producing no ill effect.", synonyms: ["harmless", "safe"]),
        VocabWord(word: "innovative", definition: "Characterized by the creation of new ideas or inventions.", synonyms: ["advanced", "original", "modern"]),
        VocabWord(word: "inscrutable", definition: "Difficult or impossible to comprehend, fathom, or interpret.", synonyms: ["mysterious", "unclear"]),
        VocabWord(word: "insidious", definition: "Causing harm in a stealthy, often gradual, manner.", synonyms: ["harmful", "sneaky"]),
        VocabWord(word: "insight", definition: "Power of acute observation and deduction.", synonyms: ["penetration", "deduction"]),
        VocabWord(word: "insightful", definition: "Possessing insight; percipient.", synonyms: ["insight", "sensible"]),
        VocabWord(word: "insinuating", definition: "To hint; to suggest tacitly while avoiding a direct statement.", synonyms: ["saying", "intimate", "hint"]),
        VocabWord(word: "insist", definition: "Or intransitive, with on or upon) To demand continually that something happen or be done; to reiterate a demand despite requests to abandon it.", synonyms: ["assert"]),
        VocabWord(word: "instigator", definition: "A person who intentionally instigates, incites, or starts something, especially one that creates trouble.", synonyms: ["starter", "troublemaker"]),
        VocabWord(word: "insubordination", definition: "The quality or state of being insubordinate; disobedience to lawful authority; specifically, an employee's failure or refusal to comply with a request or an assignment given by his/her supervisor.", synonyms: ["quality"]),
        VocabWord(word: "integrity", definition: "Steadfast adherence to a strict moral or ethical code.", synonyms: ["unity", "ethical code"]),
        VocabWord(word: "interjection", definition: "a word that expresses emotion", synonyms: ["exclamation", "outburst"]),
        VocabWord(word: "intertextual", definition: "Pertaining to intertextuality; being or involving the reference to one text in another.", synonyms: ["text based", "referential"]),
        VocabWord(word: "intoxicating", definition: "Very exciting and stimulating, like alcohol or some other stimulant.", synonyms: ["exciting", "alcoholic"]),
        VocabWord(word: "intrigue", definition: "To arouse the interest of; to fascinate.", synonyms: ["scheme"]),
        VocabWord(word: "intuitive", definition: "Easily understood or grasped by intuition.", synonyms: ["natural", "easy to use"]),
        VocabWord(word: "invoke", definition: "To call upon for help, assistance or guidance.", synonyms: ["raise", "stir", "guidance"]),
        VocabWord(word: "iota", definition: "A jot; a very small, insignificant quantity.", synonyms: ["tiny bit", "little"]),
        VocabWord(word: "irate", definition: "Extremely angry; wrathful; enraged.", synonyms: ["angry", "extremely angry"]),
        VocabWord(word: "iridescent", definition: "Producing a display of lustrous, rainbow-like colors; prismatic.", synonyms: ["shiny", "glowing"]),
        VocabWord(word: "irresponsible", definition: "Lacking a sense of responsibility; performed or acting as though without responsibility; negligent.", synonyms: ["loose", "devil may care"]),
        VocabWord(word: "irretrievably", definition: "In an irretrievable manner; irrecoverably.", synonyms: ["permanently", "forever"]),
        VocabWord(word: "irritable", definition: "Easily exasperated or excited.", synonyms: ["sensitive", "excited"]),
        VocabWord(word: "jest", definition: "To tell a joke; to talk in a playful manner; to make fun of something or someone.", synonyms: ["joke", "gag"]),
        VocabWord(word: "jittery", definition: "Nervy, jumpy, on edge.", synonyms: ["nervous", "tense"]),
        VocabWord(word: "jolly", definition: "Full of merriment and high spirits; jovial; joyous; merry.", synonyms: ["gay", "high spirits"]),
        VocabWord(word: "jovial", definition: "Cheerful and good-humoured; jolly, merry.", synonyms: ["cheerful", "friendly"]),
        VocabWord(word: "jubilant", definition: "In a state of elation.", synonyms: ["joyful", "thrilled"]),
        VocabWord(word: "just", definition: "Morally right; upright, righteous, equitable; fair.", synonyms: ["good", "fair"]),
        VocabWord(word: "kaleidoscope", definition: "An instrument consisting of a tube containing mirrors and loose, colourful beads or other objects; when the tube is looked into and rotated, a succession of symmetrical designs can be seen.", synonyms: ["colorful pattern", "changing pattern"]),
        VocabWord(word: "karma", definition: "A force or law of nature which causes one to reap what one sows; destiny; fate.", synonyms: ["yoga", "mojo", "force"]),
        VocabWord(word: "keen", definition: "Often with a prepositional phrase, or with to and an infinitive: showing a quick and ardent responsiveness or willingness; eager, enthusiastic, interested.", synonyms: ["sharp", "intense", "exquisite"]),
        VocabWord(word: "kinetic", definition: "Relating to motion.", synonyms: ["moving", "active"]),
        VocabWord(word: "kismet", definition: "Fate; a predetermined or unavoidable destiny.", synonyms: ["luck", "fortune", "fate"]),
        VocabWord(word: "kitsch", definition: "Art, decorative objects, and other forms of representation of questionable artistic or aesthetic value; a representation that is excessively sentimental, overdone, or vulgar.", synonyms: ["aesthetic value"]),
        VocabWord(word: "labyrinthine", definition: "Convoluted, baffling, confusing, perplexing.", synonyms: ["maze like", "complex"]),
        VocabWord(word: "languid", definition: "relaxed", synonyms: ["slow", "lazy"]),
        VocabWord(word: "latency", definition: "A delay, an interval between the initiation of something and the occurrence.", synonyms: ["delay", "lag"]),
        VocabWord(word: "laurels", definition: "Honors. From the Ancient Greek practice of crowning victors with a branch from the laurel bush, sacred to Apollo.", synonyms: ["award", "honors"]),
        VocabWord(word: "legendary", definition: "Having unimaginable greatness; excellent to such an extent to evoke stories.", synonyms: ["known", "fabulous", "unreal"]),
        VocabWord(word: "lethal", definition: "Of, pertaining to, or causing death; deadly; mortal; fatal.", synonyms: ["fatal", "deadly", "life threatening"]),
        VocabWord(word: "lethargic", definition: "Sluggish, slow.", synonyms: ["tired", "slow"]),
        VocabWord(word: "leverage", definition: "Any influence which is compounded or used to gain an advantage.", synonyms: ["purchase", "tool", "lever"]),
        VocabWord(word: "levity", definition: "A lightness of manner or speech, frivolity; flippancy; a lack of appropriate seriousness; an inclination to make a joke of serious matters.", synonyms: ["humor", "lightness"]),
        VocabWord(word: "lewd", definition: "Lascivious, sexually promiscuous, rude.", synonyms: ["obscene"]),
        VocabWord(word: "likewise", definition: "Also; moreover; too.", synonyms: ["also", "besides", "similarly"]),
        VocabWord(word: "limerence", definition: "An involuntary romantic infatuation with another person, especially combined with an overwhelming, obsessive need to have one's feelings reciprocated.", synonyms: ["crush", "infatuation"]),
        VocabWord(word: "litigate", definition: "To go to law; to carry on a lawsuit.", synonyms: ["process", "sue", "advocate"]),
        VocabWord(word: "litigious", definition: "Inclined to engage in lawsuits.", synonyms: ["argumentative", "legalistic"]),
        VocabWord(word: "lucid", definition: "Clear; easily understood.", synonyms: ["clear", "easy to understand"]),
        VocabWord(word: "lucrative", definition: "Producing a surplus; profitable.", synonyms: ["profitable", "well paid"]),
        VocabWord(word: "ludicrous", definition: "Idiotic or unthinkable, often to the point of being funny; amusing by being plainly incongruous or absurd.", synonyms: ["ridiculous", "absurd"]),
        VocabWord(word: "luminaries", definition: "One who is an inspiration to others; one who has achieved success in one's chosen field; a leading light.", synonyms: ["leaders"]),
        VocabWord(word: "lurking", definition: "The act of one who lurks.", synonyms: ["sneak"]),
        VocabWord(word: "macabre", definition: "Ghastly, shocking, terrifying.", synonyms: ["grim", "morbid"]),
        VocabWord(word: "madness", definition: "The state of being mad; insanity; mental disease.", synonyms: ["rage"]),
        VocabWord(word: "magnanimous", definition: "Noble and generous in spirit.", synonyms: ["generous", "forgiving"]),
        VocabWord(word: "majestic", definition: "Having qualities of splendor or royalty.", synonyms: ["proud", "noble", "impressive"]),
        VocabWord(word: "maladies", definition: "Any ailment or disease of the body; especially, a lingering or deep-seated disorder.", synonyms: ["illnesses", "sickness"]),
        VocabWord(word: "malevolent", definition: "Having or displaying ill will; wishing harm on others.", synonyms: ["evil", "harmful"]),
        VocabWord(word: "malicious", definition: "Intending to do harm; characterized by spite and malice.", synonyms: ["mean", "harmful"]),
        VocabWord(word: "malignant", definition: "Harmful, malevolent, injurious.", synonyms: ["evil", "malicious"]),
        VocabWord(word: "maligned", definition: "Assailed with contemptuous language.", synonyms: ["abused"]),
        VocabWord(word: "marred", definition: "Spoilt, cosseted, overly indulged, soft.", synonyms: ["damaged"]),
        VocabWord(word: "marrow", definition: "The substance inside bones which produces blood cells.", synonyms: ["core", "substance", "essence"]),
        VocabWord(word: "marvelous", definition: "Exciting wonder or surprise; astonishing; wonderful.", synonyms: ["incredible", "extraordinary", "tremendous"]),
        VocabWord(word: "maw", definition: "mouth", synonyms: ["hole", "trap", "mouth"]),
        VocabWord(word: "mayhem", definition: "A state or situation of great confusion, disorder, trouble or destruction; chaos.", synonyms: ["chaos", "chaotic", "havoc"]),
        VocabWord(word: "mental", definition: "Of or relating to the mind or specifically the total emotional and intellectual response of an individual to external reality.", synonyms: ["intellectual", "moral", "rational"]),
        VocabWord(word: "merit", definition: "Something deserving or worthy of positive recognition or reward.", synonyms: ["rate", "deserve", "reward"]),
        VocabWord(word: "metaphor", definition: "a figure of speech that compares two things without using \\\\\\\"like\\\\\\\" or \\\\\\\"as\\\\\\\"", synonyms: ["symbol", "analogy"]),
        VocabWord(word: "milquetoast", definition: "A person of meek or timid disposition; a person who lacks character or effectiveness.", synonyms: ["timid", "meek"]),
        VocabWord(word: "minuscule", definition: "Very small; tiny.", synonyms: ["small", "little"]),
        VocabWord(word: "minute", definition: "A unit of time which is one sixtieth of an hour.", synonyms: ["small", "little", "bit"]),
        VocabWord(word: "misanthrope", definition: "mankind hater", synonyms: ["people hater", "loner"]),
        VocabWord(word: "mischievous", definition: "Troublesome, cheeky, badly behaved, impish, naughty, disobedient; showing a fondness for causing trouble in a playful way and liking to have fun by playing harmless tricks on people or doing things they are not supposed to do.", synonyms: ["bad", "playful"]),
        VocabWord(word: "mitigate", definition: "To reduce, lessen, or decrease and thereby to make less severe or easier to bear.", synonyms: ["reduce", "lessen"]),
        VocabWord(word: "modicum", definition: "A modest, small, or trifling amount.", synonyms: ["small amount", "bit"]),
        VocabWord(word: "momentous", definition: "Outstanding in importance, of great consequence.", synonyms: ["big", "important", "significant"]),
        VocabWord(word: "morally", definition: "In terms of morals or ethics.", synonyms: ["mentally", "morality", "ethics"]),
        VocabWord(word: "morbid", definition: "Taking an interest in, or fixating on, unhealthy or unwholesome subjects such as death, decay, disease.", synonyms: ["grim", "ghoulish"]),
        VocabWord(word: "morsel", definition: "A small fragment or share of something, commonly applied to food.", synonyms: ["bit", "bite", "scrap"]),
        VocabWord(word: "munificent", definition: "Very liberal in giving or bestowing.", synonyms: ["generous", "giving"]),
        VocabWord(word: "mutinous", definition: "Of, pertaining to, or constituting mutiny.", synonyms: ["rebel"]),
        VocabWord(word: "myopic", definition: "Shortsighted; improvident.", synonyms: ["short sighted", "narrow"]),
        VocabWord(word: "myriad", definition: "A countless number or multitude.", synonyms: ["infinite", "countless", "countless number"]),
        VocabWord(word: "naive", definition: "Lacking worldly experience, wisdom, or judgement; unsophisticated.", synonyms: ["ignorant", "judgement"]),
        VocabWord(word: "narcissistic", definition: "Having an inflated idea of one's own importance.", synonyms: ["self centered", "vain"]),
        VocabWord(word: "narration", definition: "That which is narrated or recounted; an orderly recital of the details and particulars of some transaction or event, or of a series of transactions or events; a story or narrative.", synonyms: ["tale", "narrative", "yarn"]),
        VocabWord(word: "narrator", definition: "One who narrates or tells stories.", synonyms: ["story", "tells stories"]),
        VocabWord(word: "narrow-minded", definition: "Intolerant, bigoted or prejudiced.", synonyms: ["small", "little", "petty"]),
        VocabWord(word: "narrowly", definition: "Closely; by a narrow margin.", synonyms: ["close", "strictly", "tightly"]),
        VocabWord(word: "native", definition: "Born or grown in the region in which it lives or is found; not foreign or imported.", synonyms: ["natural", "domestic", "pure"]),
        VocabWord(word: "neat", definition: "Clean, tidy; free from dirt or impurities.", synonyms: ["good", "refined", "keen"]),
        VocabWord(word: "nifty", definition: "Good, smart; useful or beneficial, often in an impressively clever way.", synonyms: ["good", "cool", "keen"]),
        VocabWord(word: "nimble", definition: "Quick and light in movement or action.", synonyms: ["quick", "active", "intelligent"]),
        VocabWord(word: "noble", definition: "Having honorable qualities; having moral eminence and freedom from anything petty, mean or dubious in conduct and character.", synonyms: ["blue", "impressive"]),
        VocabWord(word: "nonpareil", definition: "unparalleled", synonyms: ["paragon"]),
        VocabWord(word: "nonsensical", definition: "Without sense; absurd.", synonyms: ["absurd"]),
        VocabWord(word: "noteworthy", definition: "Deserving attention; notable; worthy of notice.", synonyms: ["important", "significant", "remarkable"]),
        VocabWord(word: "noun", definition: "a word that names a person, place, thing, or idea", synonyms: ["name", "idea"]),
        VocabWord(word: "nourishing", definition: "That provides nourishment; nutritious.", synonyms: ["feeding", "nutrient"]),
        VocabWord(word: "novel", definition: "A work of prose fiction, longer than a novella.", synonyms: ["new", "original", "fresh"]),
        VocabWord(word: "nuanced", definition: "Having nuances; possessed of multiple layers of detail, pattern, or meaning.", synonyms: ["complex", "sensitive", "subtle"]),
        VocabWord(word: "numb", definition: "Physically unable to feel, not having the power of sensation.", synonyms: ["dead", "blunt", "dull"]),
        VocabWord(word: "obfuscating", definition: "To deliberately make more confusing in order to conceal the truth.", synonyms: ["confusing", "unclear"]),
        VocabWord(word: "oblivion", definition: "The state of forgetting completely, of being oblivious, unconscious, unaware, as when sleeping, drunk, or dead.", synonyms: ["failure", "dead"]),
        VocabWord(word: "obscure", definition: "Difficult to understand; abstruse.", synonyms: ["dark", "mist"]),
        VocabWord(word: "obsequious", definition: "obedient", synonyms: ["submissive", "eager to please"]),
        VocabWord(word: "omen", definition: "Something which portends or is perceived to portend either a good or evil event or circumstance in the future, or which causes a foreboding; a portent or augury.", synonyms: ["evil event"]),
        VocabWord(word: "onomatopoeia", definition: "a word that imitates a sound", synonyms: ["sound word", "sound imitation"]),
        VocabWord(word: "opportune", definition: "At a convenient or advantageous time.", synonyms: ["good", "right", "favorable"]),
        VocabWord(word: "opulence", definition: "Ostentatious display of wealth and luxury; plushness.", synonyms: ["wealth", "luxury"]),
        VocabWord(word: "orifice", definition: "A mouth or aperture, such as of a tube, pipe, etc.; an opening.", synonyms: ["opening", "outlet", "aperture"]),
        VocabWord(word: "ostentation", definition: "Ambitious display; vain show; display intended to excite admiration or applause.", synonyms: ["showiness", "flashiness"]),
        VocabWord(word: "ostracize", definition: "To exclude a person from a community or from society by not communicating with them or by refusing to acknowledge their presence; to refuse to associate with or talk to; to shun.", synonyms: ["exclude", "shun"]),
        VocabWord(word: "outlandish", definition: "Greatly different from common experience; bizarre, outrageous, strange.", synonyms: ["odd", "strange"]),
        VocabWord(word: "override", definition: "To counteract the normal operation of something; to countermand with orders of higher priority.", synonyms: ["reverse"]),
        VocabWord(word: "oversight", definition: "Supervision or management.", synonyms: ["supervision", "management"]),
        VocabWord(word: "oxymoron", definition: "a figure of speech that combines contradictory terms", synonyms: ["contradiction", "mixed phrase"]),
        VocabWord(word: "pacifist", definition: "One who is anti-war.", synonyms: ["anti war", "peace lover"]),
        VocabWord(word: "palatable", definition: "Pleasing to the taste, tasty.", synonyms: ["attractive", "tasty", "appealing"]),
        VocabWord(word: "panopticon", definition: "A type of prison where all the cells are visible from the center, particularly if it is not possible for those in a cell to know if they are being watched.", synonyms: ["watchtower", "surveillance"]),
        VocabWord(word: "pantomime", definition: "A traditional theatrical entertainment, originally based on the commedia dell'arte, but later aimed mostly at children and involving physical comedy, topical jokes, call and response, and fairy-tale plots.", synonyms: ["mime", "dumb show", "response"]),
        VocabWord(word: "paragon", definition: "A person of preeminent qualities, who acts as a pattern or model for others.", synonyms: ["idol", "perfection"]),
        VocabWord(word: "paragraph", definition: "a distinct section of a piece of writing", synonyms: ["section"]),
        VocabWord(word: "parasite", definition: "An organism that lives on or in another organism of a different species, deriving benefit from living on or in that other organism, while not contributing towards that other organism sufficiently to cover the cost to that other organism.", synonyms: ["sponge"]),
        VocabWord(word: "passively", definition: "In a passive manner; without conscious or self-directed action.", synonyms: ["laser", "liabilities", "adversely"]),
        VocabWord(word: "pejorative", definition: "A disparaging, belittling, or derogatory word or expression.", synonyms: ["insulting", "negative"]),
        VocabWord(word: "penitent", definition: "regret", synonyms: ["sorry", "regretful"]),
        VocabWord(word: "permeate", definition: "To enter and spread through; to pervade.", synonyms: ["diffuse", "enter"]),
        VocabWord(word: "pernicious", definition: "harmful", synonyms: ["harmful", "dangerous"]),
        VocabWord(word: "perpetuating", definition: "To make perpetual; to make continue for an indefinite time; also, to preserve from extinction or oblivion.", synonyms: ["continuing", "extending", "make perpetual"]),
        VocabWord(word: "perturbed", definition: "Disturbed; flustered.", synonyms: ["disturbed"]),
        VocabWord(word: "pestilence", definition: "Any epidemic disease that is highly contagious, infectious, virulent and devastating.", synonyms: ["epidemic", "plague", "devastating"]),
        VocabWord(word: "petulant", definition: "Childishly irritable.", synonyms: ["cranky", "childish"]),
        VocabWord(word: "phenomenal", definition: "Very remarkable; highly extraordinary; amazing.", synonyms: ["amazing", "remarkable"]),
        VocabWord(word: "phenomenon", definition: "A thing or being, event or process, perceptible through senses; or a fact or occurrence thereof.", synonyms: ["reality", "existence"]),
        VocabWord(word: "phonetically", definition: "In the way it sounds, particularly: written to describe the sound rather than the dictionary spelling.", synonyms: ["sounds like", "sound based"]),
        VocabWord(word: "pinpoint", definition: "Extremely precise or specific, especially regarding location.", synonyms: ["track", "spot", "precise"]),
        VocabWord(word: "pitiful", definition: "So appalling or sad that one feels or should feel sorry for it; eliciting pity.", synonyms: ["sad", "pathetic"]),
        VocabWord(word: "pivotal", definition: "Being of crucial importance; central, key.", synonyms: ["important", "crucial", "polar"]),
        VocabWord(word: "platitudes", definition: "An often-quoted saying that is supposed to be meaningful but has become unoriginal or hackneyed through overuse.", synonyms: ["cliches", "empty sayings"]),
        VocabWord(word: "plethora", definition: "An excessive amount or number; an abundance.", synonyms: ["many", "excess"]),
        VocabWord(word: "plundering", definition: "The act of one who plunders; pillaging or looting; plunder.", synonyms: ["looting", "stealing"]),
        VocabWord(word: "poignant", definition: "Evoking strong mental sensation, to the point of distress; emotionally moving.", synonyms: ["touching", "moving"]),
        VocabWord(word: "portrayed", definition: "Represented graphically by sketch or design or lines.", synonyms: ["represented", "depicted", "lines"]),
        VocabWord(word: "pragmatic", definition: "Practical, concerned with making decisions and actions that are useful in practice, not just theory.", synonyms: ["practical", "realistic"]),
        VocabWord(word: "precocious", definition: "Characterized by exceptionally early development or maturity.", synonyms: ["advanced", "gifted"]),
        VocabWord(word: "predicate", definition: "the part of a sentence containing the verb and stating something about the subject", synonyms: ["verb phrase"]),
        VocabWord(word: "preposition", definition: "a word that shows the relationship of a noun or pronoun to another word", synonyms: ["relational word"]),
        VocabWord(word: "prescient", definition: "Exhibiting or possessing prescience: having knowledge of, or seemingly able to correctly predict, events before they take place.", synonyms: ["aware", "farseeing"]),
        VocabWord(word: "pretentious", definition: "Motivated by an inappropriate, excessive, or unjustified desire to impress others.", synonyms: ["showy", "fake"]),
        VocabWord(word: "prim", definition: "Of a person, their manner or appearance: Formal and precise; stiffly decorous.", synonyms: ["proper", "refined", "appearance"]),
        VocabWord(word: "probe", definition: "To explore, investigate, question, test, or prove.", synonyms: ["investigation", "examine", "probing"]),
        VocabWord(word: "proclamations", definition: "A statement which is proclaimed; formal a public announcement.", synonyms: ["ads", "announcement"]),
        VocabWord(word: "proclivities", definition: "A predisposition or natural inclination, propensity, or a predilection; especially, a strong disposition or bent.", synonyms: ["tendencies", "preferences"]),
        VocabWord(word: "prone", definition: "Lying face-down.", synonyms: ["tilt", "inclined", "lying face down"]),
        VocabWord(word: "pronoun", definition: "a word that takes the place of a noun", synonyms: ["substitute noun"]),
        VocabWord(word: "propriety", definition: "Suitability, fitness; the quality of being appropriate.", synonyms: ["manners", "correctness"]),
        VocabWord(word: "prosperous", definition: "Well off; affluent.", synonyms: ["rich", "well off"]),
        VocabWord(word: "protagonist", definition: "The main character, or one of the main characters, in any story, such as a literary work or drama.", synonyms: ["friend", "champion", "booster"]),
        VocabWord(word: "proverbial", definition: "Widely known; famous; stereotypical.", synonyms: ["known", "well known", "legendary"]),
        VocabWord(word: "proxy", definition: "An agent or substitute authorized to act for another person.", synonyms: ["low level", "deputy", "subordinate"]),
        VocabWord(word: "pundit", definition: "expert", synonyms: ["initiate", "expert"]),
        VocabWord(word: "putrid", definition: "Of, relating to, or characteristic of putrefaction, especially having a bad smell, like that of rotting flesh.", synonyms: ["foul", "corrupt"]),
        VocabWord(word: "quasi", definition: "Resembling or having a likeness to the named thing.", synonyms: ["similar", "virtual", "practically"]),
        VocabWord(word: "questionable", definition: "Problematic; open to doubt or challenge.", synonyms: ["queer", "problematic"]),
        VocabWord(word: "quintessential", definition: "The fundamental essence of something.", synonyms: ["classic", "typical"]),
        VocabWord(word: "rambunctious", definition: "Boisterous, energetic, noisy, and difficult to control.", synonyms: ["rowdy", "noisy"]),
        VocabWord(word: "ramifications", definition: "An offshoot of a decision, fact etc.; a consequence or implication, especially one which complicates a situation.", synonyms: ["fork"]),
        VocabWord(word: "rampant", definition: "Unrestrained or unchecked, usually in a negative manner.", synonyms: ["upright", "erect"]),
        VocabWord(word: "ravaging", definition: "The act by which something is ravaged.", synonyms: ["destructive", "devastating"]),
        VocabWord(word: "ravenous", definition: "Very hungry.", synonyms: ["starving", "very hungry"]),
        VocabWord(word: "ravishing", definition: "Extremely beautiful.", synonyms: ["beautiful", "gorgeous"]),
        VocabWord(word: "realm", definition: "A sphere of knowledge or of influence; a domain.", synonyms: ["land", "region", "domain"]),
        VocabWord(word: "reckon", definition: "To conclude, as by an enumeration and balancing of chances; hence, to think; to suppose; -- followed by an objective clause.", synonyms: ["see", "view", "consider"]),
        VocabWord(word: "reiterate", definition: "To say or do for a second time, such as for emphasis.", synonyms: ["repeat", "say"]),
        VocabWord(word: "reminiscing", definition: "Reminiscence.", synonyms: ["remembering", "looking back"]),
        VocabWord(word: "remiss", definition: "At fault; failing to fulfill responsibility, duty, or obligations.", synonyms: ["careless", "late"]),
        VocabWord(word: "remorseful", definition: "Feeling or filled with remorse.", synonyms: ["sorry", "feeling"]),
        VocabWord(word: "repent", definition: "To feel pain, sorrow, or regret for what one has done or omitted to do; the cause for repenting may be indicated with \\\"of\\\".", synonyms: ["turn", "rue", "regret"]),
        VocabWord(word: "repentant", definition: "Feeling or showing sorrow for wrongdoing.", synonyms: ["sorry", "feeling"]),
        VocabWord(word: "repercussion", definition: "A consequence or ensuing result of some action.", synonyms: ["result", "effect"]),
        VocabWord(word: "resonate", definition: "To have an effect or impact; to influence; to engender support.", synonyms: ["connect", "echo"]),
        VocabWord(word: "revulsion", definition: "Abhorrence, a sense of loathing, intense aversion, repugnance, repulsion, horror.", synonyms: ["disgust", "horror"]),
        VocabWord(word: "rheumy", definition: "Producing rheum from the mucous membranes; especially of the eyes: filled with rheum; watery.", synonyms: ["watery", "teary"]),
        VocabWord(word: "righteous", definition: "Free from sin or guilt.", synonyms: ["just", "good", "sound"]),
        VocabWord(word: "rivulets", definition: "A small stream; a streamlet; a gill.", synonyms: ["run", "small stream"]),
        VocabWord(word: "robust", definition: "Evincing strength and health; strong; both large and healthy.", synonyms: ["strong", "rich", "stout"]),
        VocabWord(word: "saccharine", definition: "Excessively sweet in action or disposition, especially if romantic or sentimental to the point of ridiculousness; sickly sweet, syrupy.", synonyms: ["overly sweet", "sugary"]),
        VocabWord(word: "sadistic", definition: "Delighting in or feeling pleasure from the pain or humiliation of others.", synonyms: ["evil", "vicious"]),
        VocabWord(word: "salacious", definition: "Promoting sexual desire or lust.", synonyms: ["dirty", "suggestive"]),
        VocabWord(word: "sardonic", definition: "Scornfully mocking or cynical.", synonyms: ["mocking", "dry"]),
        VocabWord(word: "saunter", definition: "To stroll, or walk at a leisurely pace.", synonyms: ["stroll"]),
        VocabWord(word: "scowl", definition: "To wrinkle the brows, as in frowning or displeasure; to put on a frowning look; to look sour, sullen, severe, or angry.", synonyms: ["frown", "glare"]),
        VocabWord(word: "scurrilous", definition: "Coarse, vulgar, or abusive.", synonyms: ["abusive", "vulgar"]),
        VocabWord(word: "seraphic", definition: "Pure and sublime; angelic.", synonyms: ["angelic", "heavenly"]),
        VocabWord(word: "shoehorn", definition: "A smooth tool that assists in putting the foot into a shoe, by sliding the heel in after the toe is in place.", synonyms: ["handled", "shoe horn", "tailor"]),
        VocabWord(word: "simile", definition: "a figure of speech comparing two unlike things using \\\\\\\"like\\\\\\\" or \\\\\\\"as\\\\\\\"", synonyms: ["comparison"]),
        VocabWord(word: "skeuomorphic", definition: "Pertaining to skeuomorphs, obsolete design elements which are retained for familiarity or out of tradition, even though they no longer serve any functional purpose.", synonyms: ["old style", "decorative"]),
        VocabWord(word: "smidgen", definition: "Chiefly in the form a smidgen of: a very small amount or quantity; a bit, a trace.", synonyms: ["tiny bit", "small amount"]),
        VocabWord(word: "sordid", definition: "Distasteful, ignoble, vile, or contemptible.", synonyms: ["dirty", "sleazy"]),
        VocabWord(word: "sorrow", definition: "Unhappiness, woe.", synonyms: ["grief", "regret", "sadness"]),
        VocabWord(word: "spectrum", definition: "Specifically, a range of colours representing light of contiguous frequencies; hence electromagnetic spectrum, visible spectrum, ultraviolet spectrum, etc.", synonyms: ["number", "line", "sphere"]),
        VocabWord(word: "spellbinding", definition: "Engrossing; fascinating; gaining rapt attention; captivating.", synonyms: ["attractive"]),
        VocabWord(word: "spewing", definition: "Material spewed or vomited.", synonyms: ["throw up"]),
        VocabWord(word: "squalor", definition: "Filthiness and degradation, as from neglect or poverty.", synonyms: ["suffering", "filth", "poverty"]),
        VocabWord(word: "squandered", definition: "Not used to good advantage.", synonyms: ["lost", "wasted", "blew"]),
        VocabWord(word: "statuesque", definition: "Elegantly tall, graceful, and attractive.", synonyms: ["tall", "attractive"]),
        VocabWord(word: "stifling", definition: "That stifles.", synonyms: ["hot", "suppression"]),
        VocabWord(word: "stochastic", definition: "Random, randomly determined.", synonyms: ["random", "uncertain", "randomized"]),
        VocabWord(word: "stoicism", definition: "A real or pretended indifference to pleasure or pain; insensibility; impassiveness.", synonyms: ["self control", "calm"]),
        VocabWord(word: "strategic", definition: "Of or pertaining to strategy.", synonyms: ["important"]),
        VocabWord(word: "subject", definition: "the person or thing that performs the action in a sentence", synonyms: ["topic"]),
        VocabWord(word: "succumb", definition: "To yield to an overpowering force or overwhelming desire.", synonyms: ["yield", "overwhelming desire"]),
        VocabWord(word: "suffocating", definition: "That tends to suffocate the target; so overwhelming and lethal or life-threatening as to suffocate; suffocative.", synonyms: ["smothering", "choking"]),
        VocabWord(word: "suffuse", definition: "To spread through or over , especially as a liquid, colour or light; to bathe.", synonyms: ["light"]),
        VocabWord(word: "sullen", definition: "Having a brooding ill temper; sulky.", synonyms: ["dark", "heavy"]),
        VocabWord(word: "sumptuous", definition: "Magnificent, luxurious, splendid.", synonyms: ["luxurious", "rich"]),
        VocabWord(word: "superfluous", definition: "In excess of what is required or sufficient.", synonyms: ["extra", "unnecessary"]),
        VocabWord(word: "surliness", definition: "The property of being surly.", synonyms: ["temper"]),
        VocabWord(word: "surreptitious", definition: "Stealthy, furtive, well hidden, covert.", synonyms: ["secret", "sneaky"]),
        VocabWord(word: "swoon", definition: "To faint, to lose consciousness.", synonyms: ["pass out", "faint"]),
        VocabWord(word: "syntax", definition: "the arrangement of words and phrases to create sentences", synonyms: ["structure", "grammar"]),
        VocabWord(word: "taunting", definition: "Abusing vocally; expressing contempt or ridicule.", synonyms: ["mocking", "teasing"]),
        VocabWord(word: "tenuous", definition: "Insubstantial.", synonyms: ["weak", "thin"]),
        VocabWord(word: "theatrics", definition: "Histrionics.", synonyms: ["movies", "films", "cinema"]),
        VocabWord(word: "theme", definition: "the central topic or idea in a text", synonyms: ["topic", "motif", "central topic"]),
        VocabWord(word: "topple", definition: "To push or throw over.", synonyms: ["defeat", "tumble", "push"]),
        VocabWord(word: "tremendously", definition: "Greatly; enormously.", synonyms: ["greatly"]),
        VocabWord(word: "tremulous", definition: "Trembling, quivering, or shaking.", synonyms: ["hang", "shaking"]),
        VocabWord(word: "triad", definition: "A grouping of three.", synonyms: ["trio", "group of three"]),
        VocabWord(word: "trite", definition: "Often in reference to a word or phrase: used so many times that it is commonplace, or no longer interesting or effective; worn out, hackneyed.", synonyms: ["overused", "stale"]),
        VocabWord(word: "troglodyte", definition: "A member of a supposed prehistoric race that lived in caves or holes, a caveman.", synonyms: ["cave man"]),
        VocabWord(word: "tumultuous", definition: "Causing or characterized by tumult; chaotic, disorderly, turbulent.", synonyms: ["chaotic", "stormy"]),
        VocabWord(word: "unceremoniously", definition: "In an unceremonious manner, abruptly, without the due formalities.", synonyms: ["strongly"]),
        VocabWord(word: "undulating", definition: "Moving up and down like waves; wavy.", synonyms: ["roll", "wave", "flap"]),
        VocabWord(word: "unequivocally", definition: "In a way that leaves no doubt; in an unequivocal or unambiguous manner, unquestionably.", synonyms: ["clearly", "plainly"]),
        VocabWord(word: "unfettered", definition: "Not restricted.", synonyms: ["free", "open"]),
        VocabWord(word: "unmitigated", definition: "Total, complete, utter.", synonyms: ["pure", "total complete utter"]),
        VocabWord(word: "unorthodox", definition: "Unusual, unconventional, or idiosyncratic.", synonyms: ["unusual", "different"]),
        VocabWord(word: "unscrupulous", definition: "Without scruples; immoral.", synonyms: ["dishonest", "shady"]),
        VocabWord(word: "unsettling", definition: "That makes one troubled or uneasy; disquieting or distressing.", synonyms: ["disturbing", "upsetting"]),
        VocabWord(word: "unsophisticated", definition: "Not sophisticated; lacking sophistication.", synonyms: ["simple", "naive"]),
        VocabWord(word: "untimely", definition: "At an inopportune time.", synonyms: ["early", "wrong", "premature"]),
        VocabWord(word: "utterly", definition: "Completely; entirely; to the fullest extent.", synonyms: ["dead", "absolutely", "perfectly"]),
        VocabWord(word: "vagrants", definition: "A person without settled employment or habitation who usually supports himself or herself by begging or some dishonest means; a tramp, a vagabond.", synonyms: ["floating"]),
        VocabWord(word: "vain", definition: "Overly proud of oneself, especially concerning appearance; having a high opinion of one's own accomplishments with slight reason.", synonyms: ["proud"]),
        VocabWord(word: "vapid", definition: "Offering nothing that is stimulating or challenging.", synonyms: ["boring", "dull"]),
        VocabWord(word: "veiled", definition: "Covered by a veil.", synonyms: ["covered"]),
        VocabWord(word: "veracity", definition: "The quality of speaking or stating the truth; truthfulness.", synonyms: ["truth", "honesty"]),
        VocabWord(word: "verb", definition: "a word that expresses an action or state of being", synonyms: ["action word"]),
        VocabWord(word: "verisimilitude", definition: "appearance of being true", synonyms: ["realism", "believability"]),
        VocabWord(word: "verve", definition: "Enthusiasm, rapture, spirit, or vigour, especially of imagination such as that which animates an artist, musician, or writer, in composing or performing.", synonyms: ["energy", "enthusiasm"]),
        VocabWord(word: "vetted", definition: "Having undergone an investigation and been approved.", synonyms: ["review", "approved", "verified"]),
        VocabWord(word: "vexatious", definition: "Causing vexation or annoyance; teasing; troublesome.", synonyms: ["annoying", "irritating"]),
        VocabWord(word: "vexed", definition: "Annoyed, irritated or distressed.", synonyms: ["hard", "difficult", "troubled"]),
        VocabWord(word: "vicious", definition: "Violent, destructive and cruel.", synonyms: ["evil", "wicked", "cruel"]),
        VocabWord(word: "vigorously", definition: "With intense energy, force or vigor.", synonyms: ["strongly", "energetically"]),
        VocabWord(word: "vile", definition: "Morally low; base; despicable.", synonyms: ["evil", "wicked", "foul"]),
        VocabWord(word: "vilify", definition: "To say defamatory things about someone or something; to speak ill of.", synonyms: ["rail"]),
        VocabWord(word: "vindicated", definition: "Justified, avenged or cleared of blame.", synonyms: ["clear", "innocent"]),
        VocabWord(word: "vindictive", definition: "Having a tendency to seek revenge when wronged, vengeful.", synonyms: ["spiteful", "vengeful"]),
        VocabWord(word: "virtue", definition: "Accordance with moral principles; conformity of behaviour or thought with the strictures of morality; good moral conduct.", synonyms: ["merit", "moral excellence"]),
        VocabWord(word: "virulent", definition: "poisonous, harmful", synonyms: ["harmful", "deadly"]),
        VocabWord(word: "visage", definition: "Countenance; one's face.", synonyms: ["mug"]),
        VocabWord(word: "visceral", definition: "Of or relating to the viscera or bowels regarded as the origin of a person's emotions; hence , relating to or having deep internal feelings or sensibility.", synonyms: ["gut level", "instinctive"]),
        VocabWord(word: "vital", definition: "Necessary to the continuation of life; being the seat of life; being that on which life depends.", synonyms: ["critical", "essential", "indispensable"]),
        VocabWord(word: "vitriol", definition: "Bitterly abusive language.", synonyms: ["hatred", "abuse"]),
        VocabWord(word: "vociferous", definition: "vehement", synonyms: ["loud", "noisy"]),
        VocabWord(word: "void", definition: "Containing nothing; empty; not occupied or filled.", synonyms: ["containing nothing"]),
        VocabWord(word: "volatile", definition: "Of a price, variable or erratic.", synonyms: ["unstable", "explosive"]),
        VocabWord(word: "volition", definition: "The mental power or ability of choosing; the will.", synonyms: ["choice", "will"]),
        VocabWord(word: "voluptuous", definition: "Curvaceous and sexually attractive.", synonyms: ["curvy", "sensual"]),
        VocabWord(word: "vulnerable", definition: "More or most likely to be exposed to the chance of being attacked or harmed, either physically or emotionally.", synonyms: ["open", "weak", "tender"]),
        VocabWord(word: "wanderlust", definition: "A strong impulse or longing to travel.", synonyms: ["travel urge", "love of travel"]),
        VocabWord(word: "wayside", definition: "The side of a road or path.", synonyms: ["road", "path", "roadside"]),
        VocabWord(word: "weak-constitution", definition: "Having a physically delicate or easily weakened body.", synonyms: ["delicate"]),
        VocabWord(word: "wealthy", definition: "Possessing financial wealth; rich.", synonyms: ["rich", "loaded", "flush"]),
        VocabWord(word: "whim", definition: "A fanciful impulse, or sudden change of idea.", synonyms: ["notion", "impulse"]),
        VocabWord(word: "whimsical", definition: "Given to whimsy.", synonyms: ["arbitrary"]),
        VocabWord(word: "wise", definition: "Showing good judgement or the benefit of experience.", synonyms: ["sensible", "prudent"]),
        VocabWord(word: "wistfully", definition: "In a wistful manner.", synonyms: ["sadly", "longingly"]),
        VocabWord(word: "world-class", definition: "Of a standard that ranks among the best in the world.", synonyms: ["high quality", "grade", "top flight"]),
        VocabWord(word: "worldly", definition: "Concerned with human or earthly matters, physical as opposed to spiritual.", synonyms: ["temporal"]),
        VocabWord(word: "wrongdoings", definition: "Violation of standards of behavior.", synonyms: ["error", "abuses", "misconduct"]),
        VocabWord(word: "xenic", definition: "Strange or foreign in some way.", synonyms: ["foreign", "strange"]),
        VocabWord(word: "xenium", definition: "A gift or offering.", synonyms: ["gift", "offering"]),
        VocabWord(word: "xylograph", definition: "An engraving in wood or woodcut, especially one used in printing predating the Western tradition.", synonyms: ["woodcut", "print"]),
        VocabWord(word: "xyris", definition: "A plant in the yellow-eyed grass genus Xyris.", synonyms: ["marsh plant", "yellow eyed grass"]),
        VocabWord(word: "yare", definition: "Easily manageable and responsive to the helm; yar.", synonyms: ["good", "bound", "prompt"]),
        VocabWord(word: "yearn", definition: "To have a strong desire for something or to do something; to long for or to do something.", synonyms: ["long", "pine"]),
        VocabWord(word: "yearning", definition: "A wistful or melancholy longing.", synonyms: ["desire", "sad"]),
        VocabWord(word: "zany", definition: "Unusual and awkward in a funny, comical manner; outlandish; clownish.", synonyms: ["fool", "silly", "foolish"]),
        VocabWord(word: "zealots", definition: "A political movement in 1st-century Second Temple Judaism that sought to incite the people of Judaea Province to rebel against the Roman Empire and expel it from the Holy Land by force of arms, most notably during the First Jewish–Roman War.", synonyms: ["burners", "partisan"]),
        VocabWord(word: "zeitgeist", definition: "The spirit of the age; the taste, outlook, and spirit characteristic of a period.", synonyms: ["spirit of the times", "cultural mood"]),
        VocabWord(word: "zen", definition: "Of or related to Zen Buddhism.", synonyms: ["asia", "meditation", "zine"]),
        VocabWord(word: "zenith", definition: "Highest point or state; peak.", synonyms: ["peak", "top"]),
        VocabWord(word: "zest", definition: "Enthusiasm; keen enjoyment; relish; gusto.", synonyms: ["tang", "enthusiasm"]),
        VocabWord(word: "zingy", definition: "Full of zest.", synonyms: ["sharp", "lively"]),
        VocabWord(word: "zippy", definition: "Energetic and lively.", synonyms: ["energetic", "spirited", "lively"]),
    ]

    static let synonymsToWord: [String: VocabWord] = {
        var map: [String: VocabWord] = [:]
        for vw in vocab {
            for syn in vw.synonyms {
                map[syn.lowercased()] = vw
            }
            map[vw.word.lowercased()] = vw
        }
        return map
    }()

    static func suggestion(for typedWord: String) -> VocabWord? {
        let key = typedWord.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        return synonymsToWord[key]
    }
}
