//
//  VocabData.swift
//  Words
//
//  Created by Julia Teleki on 3/31/26.
//

import Foundation

struct VocabWord: Identifiable, Hashable {
    let id = UUID()
    let word: String
    let definition: String?
    let synonyms: [String]

    init(word: String, definition: String?, synonyms: [String] = []) {
        self.word = word
        self.definition = definition
        self.synonyms = synonyms
    }
}

enum VocabData {
    static let vocab: [VocabWord] = [
        VocabWord(word: "abhor", definition: "Definition not provided.", synonyms: ["hate", "detest", "loathe", "despise"]),
        VocabWord(word: "absolve", definition: "Definition not provided.", synonyms: ["forgive", "pardon", "exonerate", "acquit"]),
        VocabWord(word: "accompanied", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "accosted", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "acolyte", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "acrimonious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "acuity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ad nauseam", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "adjacent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "admonish", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "adulation", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "affliction", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "agile", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "akin", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "albeit", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "altercation", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "amenable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "amiable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "amoral", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "anachronism", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ancillary", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "anemic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "animosity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "antagonizing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "antecedent", definition: "a word, phrase, or clause referred to by a pronoun", synonyms: ["precursor", "prior", "previous"]),
        VocabWord(word: "apathy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "apocalypse", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "approximately", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "aptly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ardent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "asinine", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "aspirational", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "assent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "astonishing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "astounding", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "atrocious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "audacious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "audacity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "baffling", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "beatific", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bellend", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "benevolent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bile", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bitter", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bizarre", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "boorish", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "brazen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "brigade", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bright", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "brocade", definition: "rich fabric with raised pattern", synonyms: ["fabric", "textile"]),
        VocabWord(word: "brutes", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "bugger", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "callous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "capacity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "capitulate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cautious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cavalierly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ceding", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chagrin", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chaise", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "charismatic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "charitability", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "charlatan", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chaste", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chattel", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "chicanery", definition: "trickery", synonyms: []),
        VocabWord(word: "churned", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "circumnavigate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "classy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "clause", definition: "a grammatical unit that contains both a subject and a verb", synonyms: ["sentence part", "proposition"]),
        VocabWord(word: "clever", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "clusterfuck", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "coalesced", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "coherence", definition: "the quality of being logical and consistent", synonyms: ["clarity", "consistency", "logic"]),
        VocabWord(word: "cohorts", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "comical", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "compelling", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "compounded", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "comprehend", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "compunction", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "concomitantly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "condemnation", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "confection", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "confessional", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "congeal", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "conjunction", definition: "a word that joins words, phrases, or clauses", synonyms: ["connector", "linker"]),
        VocabWord(word: "consequences", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "constituency", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "constituents", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "contempt", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "contrition", definition: "remorse", synonyms: []),
        VocabWord(word: "cooing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "coursing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "covert", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "crisis", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cross", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "crusade", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cunning", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cursory", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "cynical", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dainty", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dapper", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dastardly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dauntless", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "debauchery", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "declarative", definition: "a sentence that makes a statement", synonyms: ["assertive"]),
        VocabWord(word: "decorum", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "defiant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "demarcated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "demeaning", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "demerit", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "demure", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "deplorable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "depreciating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "derision", definition: "mockery", synonyms: []),
        VocabWord(word: "desolate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "detractor", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "detritus", definition: "waste", synonyms: []),
        VocabWord(word: "devious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "diffuse", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dilapidated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "discarded", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disconcerting", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "discretion", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disembodied", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disemboweled", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disingenuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dismal", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disordered", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disquieting", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "distasteful", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "disturbed", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dreadful", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dreary", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "drily", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dubious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dull", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "duplicitous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dwell", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dynamic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "dystopian", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "earnest", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ebullient", definition: "enthusiastic, or a bubbling liquid", synonyms: []),
        VocabWord(word: "ecstatic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "effeminate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "effervescent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "egregious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "elated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "elevated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "eloquent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "eluded", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "elusive", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "emaciated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "emanating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "emboldened", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "emphysema", definition: "enlarged damaged lungs", synonyms: []),
        VocabWord(word: "emulator", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "enable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "enchanting", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "endearing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "endurance", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "enormous", definition: "very large in size", synonyms: ["big", "huge", "immense", "massive"]),
        VocabWord(word: "entitlement", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "entreatingly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "entropy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "envious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ephemeral", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "erratic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "eschews", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "esoteric", definition: "obscure", synonyms: []),
        VocabWord(word: "eviscerated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "exclamatory", definition: "a sentence that expresses strong feeling", synonyms: ["emphatic"]),
        VocabWord(word: "exorbitant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "extrapolate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "facade", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "facet", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "facetious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fallacies", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "famished", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fanged", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "farce", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fasciculation", definition: "brief, spontaneous muscle contraction", synonyms: []),
        VocabWord(word: "fascinating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fastidious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "faux", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fawn", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fecund", definition: "fertile", synonyms: []),
        VocabWord(word: "feign", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "feral", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fervor", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fetid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "flabbergasted", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "folly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "forensic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "forevermore", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "forsaken", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fossilized", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fragile", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fragment", definition: "an incomplete sentence", synonyms: ["piece", "portion", "part"]),
        VocabWord(word: "fraudulent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fraught", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "froideur", definition: "coolness, reserve between people", synonyms: []),
        VocabWord(word: "fruition", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "fruitless", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gall", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gallivanting", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gauche", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gauge", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gaunt", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "glamorous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "glowering", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gracious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "grandeur", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "gratuitous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "guise", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "haggard", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "harbinger", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "harrowing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hearty", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hedonistic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "heretic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hermeneutical", definition: "concerning interpretation", synonyms: []),
        VocabWord(word: "heroic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hierarchy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hive-mind", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hounding", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "house of cards", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "humorous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "humunculi", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hybrid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "hyperbole", definition: "an exaggerated statement", synonyms: ["exaggeration", "overstatement"]),
        VocabWord(word: "hypergamy", definition: "marrying up", synonyms: []),
        VocabWord(word: "idempotent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "idyllic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ignoramous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "imbalance", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "imbibe", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "immense", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "imminent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "impenetrable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "imperative", definition: "a sentence that gives a command", synonyms: ["command", "mandatory", "urgent"]),
        VocabWord(word: "implode", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "impropriety", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inadequacies", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inadvertently", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inane", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inanity", definition: "nonsensical remark", synonyms: []),
        VocabWord(word: "incandescent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "incantation", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "incentive", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "incoherent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "indignant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "indiscernible", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "indiscriminately", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "indulgent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inexplicable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inextricably", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "infantilization", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ingenious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "initial", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "initiative", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "innocuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "innovative", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "inscrutable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insidious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insight", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insightful", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insinuating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insist", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "instigator", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "insubordination", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "integrity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "interjection", definition: "a word that expresses emotion", synonyms: ["exclamation"]),
        VocabWord(word: "intertextual", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "intoxicating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "intrigue", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "intuitive", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "invoke", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "iota", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "irate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "iridescent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "irresponsible", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "irretrievably", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "irritable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "jest", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "jittery", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "jolly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "jovial", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "jubilant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "just", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "kaleidoscope", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "karma", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "keen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "kinetic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "kismet", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "kitsch", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "labyrinthine", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "languid", definition: "relaxed", synonyms: []),
        VocabWord(word: "latency", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "laurels", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "legendary", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lethal", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lethargic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "leverage", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "levity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lewd", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "likewise", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "limerence", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "litigate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "litigious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lucid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lucrative", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ludicrous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "luminaries", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "lurking", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "macabre", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "madness", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "magnanimous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "majestic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "maladies", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "malevolent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "malicious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "malignant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "maligned", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "marred", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "marrow", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "marvelous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "maw", definition: "mouth", synonyms: []),
        VocabWord(word: "mayhem", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "mental", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "merit", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "metaphor", definition: "a figure of speech that compares two things without using \"like\" or \"as\"", synonyms: ["analogy", "symbol"]),
        VocabWord(word: "milquetoast", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "minuscule", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "minute", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "misanthrope", definition: "mankind hater", synonyms: []),
        VocabWord(word: "mischievous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "mitigate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "modicum", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "momentous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "morally", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "morbid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "morsel", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "munificent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "mutinous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "myopic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "myriad", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "naive", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "narcissistic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "narration", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "narrator", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "narrow-minded", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "narrowly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "native", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "neat", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "nifty", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "nimble", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "noble", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "nonpareil", definition: "unparalleled", synonyms: []),
        VocabWord(word: "nonsensical", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "noteworthy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "noun", definition: "a word that names a person, place, thing, or idea", synonyms: ["name"]),
        VocabWord(word: "nourishing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "novel", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "nuanced", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "numb", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "obfuscating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "oblivion", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "obscure", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "obsequious", definition: "obedient", synonyms: []),
        VocabWord(word: "omen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "onomatopoeia", definition: "a word that imitates a sound", synonyms: ["sound word"]),
        VocabWord(word: "opportune", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "opulence", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "orifice", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ostentation", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ostracize", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "outlandish", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "override", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "oversight", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "oxymoron", definition: "a figure of speech that combines contradictory terms", synonyms: ["contradiction"]),
        VocabWord(word: "pacifist", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "palatable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "panopticon", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pantomime", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "paragon", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "paragraph", definition: "a distinct section of a piece of writing", synonyms: ["section"]),
        VocabWord(word: "parasite", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "passively", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pejorative", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "penitent", definition: "regret", synonyms: []),
        VocabWord(word: "permeate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pernicious", definition: "harmful", synonyms: []),
        VocabWord(word: "perpetuating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "perturbed", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pestilence", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "petulant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "phenomenal", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "phenomenon", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "phonetically", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pinpoint", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pitiful", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pivotal", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "platitudes", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "plethora", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "plundering", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "poignant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "portrayed", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pragmatic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "precocious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "predicate", definition: "the part of a sentence containing the verb and stating something about the subject", synonyms: ["verb phrase"]),
        VocabWord(word: "preposition", definition: "a word that shows the relationship of a noun or pronoun to another word", synonyms: ["relational word"]),
        VocabWord(word: "prescient", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pretentious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "prim", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "probe", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "proclamations", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "proclivities", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "prone", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pronoun", definition: "a word that takes the place of a noun", synonyms: ["substitute noun"]),
        VocabWord(word: "propriety", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "prosperous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "protagonist", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "proverbial", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "proxy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "pundit", definition: "expert", synonyms: []),
        VocabWord(word: "putrid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "quasi", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "questionable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "quintessential", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "rambunctious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ramifications", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "rampant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ravaging", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ravenous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "ravishing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "realm", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "reckon", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "reiterate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "reminiscing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "remiss", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "remorseful", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "repent", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "repentant", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "repercussion", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "resonate", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "revulsion", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "rheumy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "righteous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "rivulets", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "robust", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "saccharine", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sadistic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "salacious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sardonic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "saunter", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "scowl", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "scurrilous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "seraphic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "shoehorn", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "simile", definition: "a figure of speech comparing two unlike things using \"like\" or \"as\"", synonyms: ["comparison"]),
        VocabWord(word: "skeuomorphic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "smidgen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sordid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sorrow", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "spectrum", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "spellbinding", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "spewing", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "squalor", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "squandered", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "statuesque", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "stifling", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "stochastic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "stoicism", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "strategic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "subject", definition: "the person or thing that performs the action in a sentence", synonyms: ["topic"]),
        VocabWord(word: "succumb", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "suffocating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "suffuse", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sullen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "sumptuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "superfluous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "surliness", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "surreptitious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "swoon", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "syntax", definition: "the arrangement of words and phrases to create sentences", synonyms: ["structure", "grammar"]),
        VocabWord(word: "taunting", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "tenuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "theatrics", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "theme", definition: "the central topic or idea in a text", synonyms: ["topic", "motif"]),
        VocabWord(word: "topple", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "tremendously", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "tremulous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "triad", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "trite", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "troglodyte", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "tumultuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unceremoniously", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "undulating", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unequivocally", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unfettered", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unmitigated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unorthodox", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unscrupulous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unsettling", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "unsophisticated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "untimely", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "utterly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vagrants", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vain", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vapid", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "veiled", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "veracity", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "verb", definition: "a word that expresses an action or state of being", synonyms: ["action word"]),
        VocabWord(word: "verisimilitude", definition: "appearance of being true", synonyms: []),
        VocabWord(word: "verve", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vetted", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vexatious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vexed", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vicious", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vigorously", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vile", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vilify", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vindicated", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vindictive", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "virtue", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "virulent", definition: "poisonous, harmful", synonyms: []),
        VocabWord(word: "visage", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "visceral", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vital", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vitriol", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vociferous", definition: "vehement", synonyms: []),
        VocabWord(word: "void", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "volatile", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "volition", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "voluptuous", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "vulnerable", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wanderlust", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wayside", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "weak-constitution", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wealthy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "whim", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "whimsical", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wise", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wistfully", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "world-class", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "worldly", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "wrongdoings", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "xenic", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "xenium", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "xylograph", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "xyris", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "yare", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "yearn", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "yearning", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zany", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zealots", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zeitgeist", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zen", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zenith", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zest", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zingy", definition: "Definition not provided.", synonyms: []),
        VocabWord(word: "zippy", definition: "Definition not provided.", synonyms: []),
    ]

    static let synonymsToWord: [String: VocabWord] = {
        var map: [String: VocabWord] = [:]
        for vw in vocab {
            for syn in vw.synonyms {
                map[syn.lowercased()] = vw
            }
            map[vw.word.lowercased()] = vw
        }
        return map
    }()

    static func suggestion(for typedWord: String) -> VocabWord? {
        let key = typedWord.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        return synonymsToWord[key]
    }
}
